import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Config } from 'sst/node/config';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>nextjsenv</h1>
        <ul>
          <li>NEXT_PUBLIC_ENV_VAR: {process.env.NEXT_PUBLIC_ENV_VAR} </li>
          {/* <li>SECRET_ENV_VAR: {process.env.SECRET_ENV_VAR} </li> */}
          {/*SECRET_ENV_VAR Error: Text content does not match server-rendered HTML Server: "VARIABLE" Client: " "*/}
          <li>
            NEXT_PUBLIC_APP_DEFAULT_FUNCTION_ENV:
            {process.env.NEXT_PUBLIC_APP_DEFAULT_FUNCTION_ENV}
          </li>
          {/* <li>
            SECRET_APP_DEFAULT_FUNCTION_ENV:
            {process.env.SECRET_APP_DEFAULT_FUNCTION_ENV}
          </li> */}
          {/*SECRET_ENV_VAR Error: Text content does not match server-rendered HTML Server: "VARIABLE" Client: " "*/}
          <li>
            NEXT_PUBLIC_CONFIG_PARAM_ENV:
            {process.env.NEXT_PUBLIC_CONFIG_PARAM_ENV}
            {/* stage-sst-config-Site/NEXT_PUBLIC_CONFIG_PARAM_ENV */}
          </li>
          {/* <li>
            SECRET_CONFIG_PARAM_ENV: {process.env.SECRET_CONFIG_PARAM_ENV}
          </li> */}
          {/*SECRET_ENV_VAR Error: Text content does not match server-rendered HTML Server: "VARIABLE" Client: " "*/}
          <li>
            NEXT_PUBLIC_CONFIG_PARAM_BIND:
            {process.env.NEXT_PUBLIC_CONFIG_PARAM_BIND}
          </li>
          {/* <li>
            SECRET_CONFIG_PARAM_BIND: {process.env.SECRET_CONFIG_PARAM_BIND}
          </li> */}
          {/*SECRET_ENV_VAR Error: Text content does not match server-rendered HTML Server: "VARIABLE" Client: " "*/}
          <li>
            NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND:
            {process.env.NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND}
          </li>
          {/* <li>
            SECRET_CONFIG_PARAM_FUNCTION_BIND:
            {process.env.SECRET_CONFIG_PARAM_FUNCTION_BIND}
          </li> */}
          {/*SECRET_ENV_VAR Error: Text content does not match server-rendered HTML Server: "VARIABLE" Client: " "*/}
        </ul>

        <h1>NEXT BIND</h1>
        {/* 
            When adding a reference to Config.VARIABLE the app throws the following error
            ./node_modules/sst/node/util/index.js
            Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
            You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
            Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
            Import trace for requested module:
            ./node_modules/sst/node/util/index.js
            ./node_modules/sst/node/config/index.js

            uppon adding the following to next.config.js the error goes away
            // @type {import('next').NextConfig}
            // const nextConfig = {
            //   reactStrictMode: true,
            //   webpack: (config) => {
            //     // this will override the experiments
            //     config.experiments = { ...config.experiments, topLevelAwait: true };
            //     // this will just update topLevelAwait property of config.experiments
            //     // config.experiments.topLevelAwait = true
            //     return config;
            //   },
            // };

            // module.exports = nextConfig;

            This does successfuly deploy to prod
        */}

        <ul>
          {/* AFTER TOPLEVEL AWAIT CHAGNE
                Error: Cannot find the SST_APP environment variable. 
                This is usually the case when you are using an older version of SST.
                Please update SST to the latest version to use the SST Config feature.*/}
          {/* <li>
            NEXT_PUBLIC_CONFIG_PARAM_BIND:
            {Config.NEXT_PUBLIC_CONFIG_PARAM_BIND}
          </li> */}
          {/* <li>SECRET_CONFIG_PARAM_BIND: {Config.SECRET_CONFIG_PARAM_BIND}</li> */}
          {/* <li>
            NEXT_PUBLIC_CONFIG_PARAM_BIND_CODE:
            {Config.NEXT_PUBLIC_CONFIG_PARAM_BIND_CODE}
          </li> */}
          {/* <li>
            SECRET_CONFIG_PARAM_BIND_CODE:
            {Config.SECRET_CONFIG_PARAM_BIND_CODE}
          </li> */}
          {/* <li>
            SECRET_CONFIG_SECRET_NEXT_BIND:
            {Config.SECRET_CONFIG_SECRET_NEXT_BIND}
          </li> */}
        </ul>

        <h1>APP BIND</h1>
        <ul>
          {/* Error: Cannot use Config.VARIABLE. Please make sure it is bound to this function. */}
          {/* <li>
            NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND:
            {Config.NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND}
          </li> */}
          {/* <li>
            SECRET_CONFIG_PARAM_FUNCTION_BIND:
            {Config.SECRET_CONFIG_PARAM_FUNCTION_BIND}
          </li> */}
          {/* <li>
            NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND_CODE:
            {Config.NEXT_PUBLIC_CONFIG_PARAM_FUNCTION_BIND_CODE}
          </li> */}
          {/* <li>
            SECRET_CONFIG_PARAM_FUNCTION_BIND_CODE:
            {Config.SECRET_CONFIG_PARAM_FUNCTION_BIND_CODE}
          </li> */}
          {/* <li>
            SECRET_CONFIG_SECRET_FUNCTION_BIND_CODE:
            {Config.SECRET_CONFIG_SECRET_FUNCTION_BIND_CODE}
          </li> */}
        </ul>

        <h1>FUNCTION ENV</h1>
        <ul>
          <li>
            NEXT_PUBLIC_APP_DEFAULT_ENV_VAR:
            {process.env.NEXT_PUBLIC_APP_DEFAULT_ENV_VAR}
            {/* No errors ofcourse, but no value */}
          </li>
          <li>
            SECRET_APP_DEFAULT_ENV_VAR:{process.env.SECRET_APP_DEFAULT_ENV_VAR}
            {/* No errors ofcourse, but no value */}
          </li>
        </ul>
      </main>
    </>
  );
}
